# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app_config.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='app_config.proto',
  package='SAP',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x10\x61pp_config.proto\x12\x03SAP\"6\n\x18\x41pplicationConfiguration\x12\x1a\n\x12supportedCountries\x18\x07 \x03(\tb\x06proto3'
)




_APPLICATIONCONFIGURATION = _descriptor.Descriptor(
  name='ApplicationConfiguration',
  full_name='SAP.ApplicationConfiguration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='supportedCountries', full_name='SAP.ApplicationConfiguration.supportedCountries', index=0,
      number=7, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=79,
)

DESCRIPTOR.message_types_by_name['ApplicationConfiguration'] = _APPLICATIONCONFIGURATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ApplicationConfiguration = _reflection.GeneratedProtocolMessageType('ApplicationConfiguration', (_message.Message,), {
  'DESCRIPTOR' : _APPLICATIONCONFIGURATION,
  '__module__' : 'app_config_pb2'
  # @@protoc_insertion_point(class_scope:SAP.ApplicationConfiguration)
  })
_sym_db.RegisterMessage(ApplicationConfiguration)


# @@protoc_insertion_point(module_scope)
